# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: DEV CI
on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone registry from github.
        uses: actions/checkout@v2

      - name: Use node version
        uses: actions/setup-node@v2
        with:
            node-version: "12.x"
            cache: 'npm'

      - name: Install dependencies with package-lock.json
        run: npm ci

      - name: Test
        run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone registry from github.
        uses: actions/checkout@v2

      - name: Use node version
        uses: actions/setup-node@v2
        with:
            node-version: "12.x"
            cache: 'npm'

      - name: Install dependencies with package-lock.json
        run: npm ci

      - name: Build
        run: npm run build

